import Divider from "@mui/material/Divider";
import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { useEffect } from "react";
import Container from "../../components/Container/Container";

const lastUpdated = "April 4, 2026";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <Stack spacing={1}>
      <Typography variant="h5" sx={{ fontSize: { xs: "1.15rem", md: "1.3rem" } }}>
        {title}
      </Typography>
      <Typography color="text.secondary">{children}</Typography>
    </Stack>
  );
}

function PrivacyPolicy() {
  useEffect(() => {
    document.title = "Privacy Policy | ToolFerry";
  }, []);

  return (
    <Container>
      <Paper
        sx={{
          p: { xs: 3, md: 4.5 },
          borderRadius: 0,
          border: "1px solid rgba(11, 31, 51, 0.08)",
          background:
            "linear-gradient(180deg, rgba(255,255,255,0.97) 0%, rgba(247,250,250,0.95) 100%)",
          boxShadow: "0 16px 40px rgba(11, 31, 51, 0.05)",
        }}
      >
        <Stack spacing={2.5} divider={<Divider flexItem />}>
          <Stack spacing={1}>
            <Typography variant="h2" sx={{ fontSize: { xs: "1.75rem", md: "2.4rem" } }}>
              Privacy Policy
            </Typography>
            <Typography color="text.secondary">Last updated: {lastUpdated}</Typography>
          </Stack>

          <Section title="Overview">
            This Privacy Policy explains how ToolFerry collects, uses, stores, and
            protects information when you use this website. By accessing or using
            ToolFerry, you agree to the practices described in this Privacy Policy.
          </Section>

          <Section title="Information We Collect">
            ToolFerry is designed to provide browser-based calculators and utility
            tools. At this time, we do not require account registration and we do not
            intentionally collect sensitive personal information through the normal use
            of the site. We may receive technical information such as browser type,
            device type, IP address, approximate location derived from IP, referring
            pages, and basic usage logs that are typically generated by hosting,
            security, or analytics infrastructure.
          </Section>

          <Section title="How We Use Information">
            We may use information to operate the website, improve performance and user
            experience, maintain security, detect abuse or technical issues, comply with
            legal obligations, and communicate in response to direct inquiries sent to
            us.
          </Section>

          <Section title="Cookies and Similar Technologies">
            ToolFerry may use cookies, local storage, or similar technologies that are
            reasonably necessary to run the website, remember preferences, measure
            traffic, or improve functionality. We currently use Google Analytics, which
            may place cookies or use similar technologies to help us understand site
            usage and traffic patterns. Third-party services that support the site may
            also use cookies or similar technologies subject to their own policies.
          </Section>

          <Section title="Third-Party Services">
            We may rely on third-party providers for hosting, infrastructure, font
            delivery, analytics, security, embedded content, advertising, or other
            operational support. This includes Google Analytics for measuring page views,
            traffic sources, and general usage trends. Those providers may process
            technical information as needed to perform services on our behalf or under
            their own applicable terms.
          </Section>

          <Section title="Data Sharing">
            We do not sell personal information in the ordinary course of operating
            ToolFerry. We may disclose information if required by law, to protect our
            rights or users, to enforce our terms, or in connection with a merger,
            acquisition, financing, restructuring, sale of assets, or similar business
            transaction.
          </Section>

          <Section title="Data Retention">
            We retain information only for as long as reasonably necessary for the
            purposes described in this policy, including operating the site, maintaining
            security records, resolving disputes, and complying with legal obligations.
          </Section>

          <Section title="Your Choices">
            You may be able to control cookies and similar technologies through your
            browser or device settings. If you contact us directly and want us to review
            or delete information you provided voluntarily, you may request that by
            emailing us, subject to applicable law and legitimate recordkeeping needs.
          </Section>

          <Section title="Children's Privacy">
            ToolFerry is not intended for children under the age of 13, and we do not
            knowingly collect personal information from children under 13. If you
            believe a child has provided personal information, contact us so we can
            review and address the issue.
          </Section>

          <Section title="International Use">
            If you access ToolFerry from outside the country where the website is
            operated, your information may be processed in other jurisdictions where
            privacy laws may differ from those in your location.
          </Section>

          <Section title="Changes to This Policy">
            We may update this Privacy Policy from time to time. Any changes become
            effective when the revised version is posted on this page with an updated
            effective date. Continued use of the website after changes are posted
            constitutes acceptance of the revised policy.
          </Section>

          <Section title="Contact">
            If you have questions about this Privacy Policy, contact us at
            toolferryonline@gmail.com.
          </Section>
        </Stack>
      </Paper>
    </Container>
  );
}

export default PrivacyPolicy;
